services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fulll\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

  Fulll\App\CommandHandler\:
    resource: '../src/App/CommandHandler'
    tags: ['messenger.message_handler']

  Fulll\Infra\Doctrine\FleetRepositoryDoctrine:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.entity_manager'
      $env: '%kernel.environment%'

  Fulll\Domain\Repository\FleetRepositoryInterface:
    alias: Fulll\Infra\Doctrine\FleetRepositoryDoctrine
    public: false
